### ISSUE TITLE
Barra preta superior de usuário aparecendo em cabanga

### ISSUE THREAD

**Issue by misawsneto** [XARXTeam/bugs#119]
Ambiente: https://cabanga.xarx.rocks
Descrição: Ver imagem

![image](https://user-images.githubusercontent.com/1959468/43992477-12dddc6a-9d55-11e8-8630-854c4bf9e0de.png)

Como reproduzir: quando faço login e volto ao frontend.

**Comment by wagnerpaxs** [comment]
Criada uma opção no XARX Options para desativar a barra. Irá para o ar no próximo deploy. Por hora, editei o usuário admxarx e coloquei no perfil dele para não mostrar a barra.
