### ISSUE TITLE
Modal de login, com social login desativado, ainda exibindo --- ou --- 

### ISSUE THREAD

**Issue by misawsneto** [XARXTeam/bugs#120]
Ambiente: https://cabanga.xarx.rocks
Descrição: Ver imagem abaixo
![image](https://user-images.githubusercontent.com/1959468/43995145-3aac4aae-9d7f-11e8-9d46-bea834ee467a.png)
Como reproduzir: clicar no botão de "entrar/login"

**Comment by wagnerpaxs** [comment]
Corrigido, vou fazer merge das branchs.
