### ISSUE TITLE
Mensagem de erro ao tentar fazer comentário

### ISSUE THREAD

**Issue by andreatavares** [XARXTeam/bugs#22]
No app, sem estar logado, sem permitir a localização, ao tentar fazer comentário é exibida mensagem: 'Oops! Desculpe, algo deu erro. Reiniciar app'. 
Na Play Store tem avaliação de usuário sobre isso(Gustavo Cavalcante, 21/12/2017).
**Obs: na OAB não tem comentário.**

**Comment by lcassiol** [comment]
Fix realizado, não estava validando dentro do post se era permitido comentar, por isso o erro.

**Comment by andreatavares** [comment]
Resolvido.
