### ISSUE TITLE
No widget de 'Leia Mais' aparecem os posts 'Diretoria' e 'Fale Conosco' 

### ISSUE THREAD

**Issue by andreatavares** [XARXTeam/bugs#24]
Na subseccional Palmares, no post 'Entrega da Reforma da Sede da OAB Palmares', do dia 19/12/2017.

**Comment by lcassiol** [comment]
Andrea eu tava olhando aqui esses que estão aparecendo são do tipo POST, aí como o elasticSearch indexa noticias do tipo POST eles acabaram sendo indexados, eu não sei ainda como resolver esse problema, acho que teremos que criar uma blacklist pra poder resolver esse problema na hora da indexação, ou se essas paginas não fossem do tipo POST, no PorAqui é assim tambem?
