### ISSUE TITLE
Anúncio duplicado

### ISSUE THREAD

**Issue by andreatavares** [XARXTeam/bugs#26]
A página https://poraqui.news/temaqui/ mostra 2 anúncios duplicados. São o mesmo cadastro sendo exibido duas vezes. **Pelo admin do Wordpress não existe essa duplicação**. Os anúncios são esses:
https://poraqui.news/temaqui/foco-sala-de-estudos/
https://poraqui.news/temaqui/winnerclass-sala-de-estudos/

No app também exibe essa duplicação.

**Comment by lenilsonjr** [comment]
Provavelmente relacionado ao Java e Elasticsearch. @lcassiol pega essa.

**Comment by andreatavares** [comment]
Resolvido.
