### ISSUE TITLE
Casa de chá, Coração da Cidade e Bruno Bezerra sem a foto

### ISSUE THREAD

**Issue by andreatavares** [XARXTeam/bugs#35]
No widget de colaboradores Casa de chá, Coração da Cidade e Bruno Bezerra está sem a foto(ou logo).
![captura de tela de 2018-03-07 13-29-58](https://user-images.githubusercontent.com/25616105/37104912-a4d50298-220c-11e8-953b-cb24f1faaddc.png)
![captura de tela de 2018-03-07 13-30-11](https://user-images.githubusercontent.com/25616105/37104913-a4f9d0a0-220c-11e8-83fd-3f986baf058f.png)
![captura de tela de 2018-03-07 13-32-49](https://user-images.githubusercontent.com/25616105/37104915-a528c25c-220c-11e8-85da-16008656f0ae.png)
![captura de tela de 2018-03-07 13-31-45](https://user-images.githubusercontent.com/25616105/37104917-a573e73c-220c-11e8-8680-8e1a09e916cc.png)

**Comment by lenilsonjr** [comment]
Corrigido no commit #eec8ef6 com a ajuda do @wagnerpaxs.
