### ISSUE TITLE
No comentário fica a foto do anúncio ao invés da foto do usuário

### ISSUE THREAD

**Issue by andreatavares** [XARXTeam/bugs#39]

**Comment by lcassiol** [comment]
People este tipo de coisa foi proposital, foi definida quando o criador do anuncio escreve um comentário o mesmo vai aparecer como o nome do anuncio e a foto correspondente, para a gente poder deixar que o anuncio seja respondido por ele, como não o anuncio não foi criado por um perfil, ele foi criado por um usuário.
