### ISSUE TITLE
[App Android]Filtro não exibe todos os itens cadastrados

### ISSUE THREAD

**Issue by andreatavares** [XARXTeam/bugs#73]
Ao filtrar por uma dessas categorias
- Doceria
- Escolas

O app exibe todos os classificados cadastrados.

**Comment by lcassiol** [comment]
O app está exibindo todos os classificados cadastrados? Talvez algo aconteça no cliente, pois o endpoint de busca é esse aqui:
https://poraqui-staging.trixapp.net/api/classifieds/search?page=0&size=30&categoryNames=Escola

No Wordpress a quantidade mostrada para **escola** é a seguinte: 
EscolaEditar | Edição rápida \| Excluir \| Ver | —Sem descrição | escola | **12**

E o resultado da busca no endpoint é o seguinte:
![resultbuscaclassifiedescola](https://user-images.githubusercontent.com/9991290/38996093-cbf8fd86-43c0-11e8-8b7a-86499d411a7f.png)


**Doceria:**
https://poraqui-staging.trixapp.net/api/classifieds/search?page=0&size=30&categoryNames=Doceria

no wordpress:

DoceriaEditar | Edição rápida \| Excluir \| Ver | —Sem descrição | doceria | **10**

E o resultado da busca
![resultbuscaclassifieddoceria](https://user-images.githubusercontent.com/9991290/38996402-7e5a673a-43c1-11e8-9781-5feddf7892df.png)

Vou dar uma analisada melhor sobre o problema agora utilizando o cliente, não fechei a Issue por ainda não ter resolvido o problema

**Comment by andreatavares** [comment]
Resolvido.
