### ISSUE TITLE
[Android-Cupom] Botão do temaqui na tela de detalhes retorna um erro estranho

### ISSUE THREAD

**Issue by misawsneto** [XARXTeam/bugs#82]
Descrição:
Na tela de detalhes de cupom, quando clico no botão que leva ao temaqui, um erro relacionado à estação é exibido.

Comportamento esperado:
Navegar até o item do temaqui relacionado ao cupom

Reprodução:
1 - Navegar até a tela de detalhes de um determinado cupom
2 - Clicar em no botão do temaqui

Ambiente:
Android versão 2.1.03

![screenshot_20180424-165615](https://user-images.githubusercontent.com/1959468/39211007-bb7148e6-47e0-11e8-9beb-1d139c29a115.png)

**Comment by lcassiol** [comment]
Até onde eu percebi esse erro ocorre por causa que o cupom não possui classificado, sendo assim vou colocar para esconder o botão do classificado neste cenario.

Estou tentando colocar agora pra distribuir melhor o espaço quando ocorrer este cenario
