### ISSUE TITLE
Ao abrir uma notificação enquanto se está lendo uma outra noticia, a noticia da notificação não abre

### ISSUE THREAD

**Issue by lenilsonjr** [XARXTeam/bugs#9]

**Comment by lcassiol** [comment]
Não consegui corrigir ainda, pois quando eu estou debugando o erro não acontece, e passei um tempo tentando entender e ainda não cheguei ao resultado para saber o que acontece, me parece que a requisição para abrir o novo post nem é feita. Estou focando em uma outra task para dar mais valor a sprint nesse momento e vou tentar voltar para esse bug 

Eu passei um tempo ontem tentando investigar esse erro, percebi mais ou menos o formato do problema, quando o aplicativo está aberto e a notificação chega e quando o aplicativo está fechado, existe o cenário em que 

- Se o app já estiver aberto e você receber a primeira notificação e abrir, vai abrir normalmente, se você receber a segunda também vai abrir independente do tempo em que estiver com a noticia aberta

- Consegui reproduzir o problema quando **o aplicativo estava fechado, a primeira notificação está abrindo, se eu receber imediatamente a segunda abre normalmente, porém se eu passar um tempo inativo, com apenas a noticia aberta sem fazer algo e receber uma segunda notificação é quando o cenário de não abrir ocorre**

**Comment by andreatavares** [comment]
Não consegui reproduzir na última versão de app que testei(2.0.24).
