### ISSUE TITLE
[Web-Agenda] Paginação

### ISSUE THREAD

**Issue by misawsneto** [XARXTeam/bugs#90]
Descrição:
Existem 28 eventos de agenda publicados. Apenas 24 são exibidos na home de agenda. Acho que temos um problema de paginação.

Comportamento esperado:
Exibir um botão de "carregar mais"para mostrar mais itens

Reprodução:
1 - Navegar até a home da agenda
2 - Fazer scroll até o fim da página e perceber que o botão de carregar mais não é exibido.

Ambiente:
Chrome: Versão 05/02/2018

**Comment by andreatavares** [comment]
Solved.
